version: "3.9"
services:
 app-db:
    image: "postgres:14.6-alpine"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB-${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
 pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - app-db
    profiles:
      - dev
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "1080:80"
volumes:
  main-db-postgres-data: {}
