version: "3.9"
services:
 db:
    image: "postgres:14.6-alpine"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB-${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  # app:
  #   build:
  #     context: .
  #     args:
  #       PORT: ${PORT}
  #   ports:
  #     - "${PORT}:${PORT}"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     - PORT=${PORT}
  #     - DB_URI=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
 
volumes:
  postgres:
