version: "3.9"
services:
  app:
    build:
      context: .
      args:
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=${PORT}
      - DB_URI=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
  db:
    image: "postgres:14.6-alpine"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - PG_PORT=${DB_PORT}
      - PG_USER=${DB_USER}
      - PG_PASS=${DB_PASS}
      - PG_DB-${DB_NAME}
    healthcheck:
      test: []
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres:
