version: "3.9"

services:
  postgresql:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/postgres/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/postgres/data/pgdata
      
volumes:
  postgres-volume:
